export const profileData = [
  {
    name: "Braden",
    image: require("../../assets/images/braden.jpg"),
    college: "McGill University",
    major: "Computer Science",
    year: 3,
    age: 19,
    ethnicity: "asian",

    bio: "A passionate developer who loves React Native!",
    socialLinks: {
      instagram: "https://www.instagram.com/braden_wei/",
      spotify: "abc",
    },
    preferences: {
      nightOwl: true,
      smoking: false,
      drinking: false,
      pets: false,
      vegan: false,
      cleanliness: 5,
    },
  },
  {
    name: "Alenna",
    image: require("../../assets/images/allena.jpg"),
    college: "McGill University",
    major: "Computer Science",
    year: 2,
    age: 20,
    ethnicity: "asian",

    bio: "Hello World!",
    socialLinks: {
      instagram: "https://www.instagram.com/allennatang",
      spotify: "abc",
    },
    preferences: {
      nightOwl: true,
      smoking: false,
      drinking: false,
      pets: false,
      vegan: false,
      cleanliness: 5,
    },
  },
  {
    name: "Bill",
    image: require("../../assets/images/bill.jpg"),
    college: "McGill University",
    major: "Computer Science",
    year: 2,
    age: 20,
    ethnicity: "asian",

    bio: "Hello World!",
    socialLinks: {
      instagram: "https://www.instagram.com/bill.skills.01",
      spotify: "abc",
    },
    preferences: {
      nightOwl: true,
      smoking: false,
      drinking: false,
      pets: false,
      vegan: false,
      cleanliness: 5,
    },
  },
  {
    name: "Tavi",
    image: require("../../assets/images/tavi.jpg"),
    college: "McGill University",
    major: "Computer Science",
    year: 2,
    age: 20,
    ethnicity: "asian",
    religion: "non",
    bio: "Passionate software developer with a love for solving complex problems. Adept at building user-friendly applications using React Native and JavaScript. Enthusiastic about AI, open-source, and collaborative teamwork. Enjoys hiking, photography, and exploring creative hobbies. Lifelong learner eager to innovate and contribute to impactful projects in technology and beyond.Hello World!",
    priceRangeLow: 1000,
    priceRangeHigh: 2000,
    socialLinks: {
      instagram: "https://www.instagram.com/tavi_river",
      spotify: "abc",
    },
    preferences: {
      nightOwl: true,
      smoking: false,
      drinking: false,
      pets: false,
      vegan: false,
      cleanliness: 5,
    },
  },
];
